config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path, include
from allauth.socialaccount.providers.google import views as google_views

urlpatterns = [
    path('control_menu/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/google/login/', google_views.oauth2_login, name='google_login'),
    path('accounts/google/login/callback/', google_views.oauth2_callback, name='google_callback'),
    path('cookie/', include('more.urls')),
    path('', include(('more.urls', 'config'), namespace='more'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

more/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path('', views.home, name='home'),
    path('submit_form/', views.submit_form, name='submit_form'),
    path('about/', views.about, name='about'),
    path('chocolate/', views.chocolate, name='chocolate'),
    path('contact/', views.contact, name='contact'),
    path('testimonial/', views.testimonial, name='testimonial'),
    path('login/', views.login, name='key'),
    path('product_form/', views.product_form, name='product_form'),
    path('email_form/', views.email_form, name='email_form'),
    path('review_form/', views.review_form, name='review_form'),
    path('reviews/', views.review_list, name='review_list'),
    path('politica/', views.politica, name='politica'),
    path('product/<int:product_id>/', views.view_product, name='view_product'),
    path('log/', views.log, name='log'),
    path('buy_vip/', views.buy_vip, name='buy_vip'),
    path('process_payment/', views.process_payment, name='process_payment'),
    path('success/', views.success_view, name='success_view'),
    path('accounts/login/None', views.profile1, name="profile1"),
    path('set_cookie/', views.set_cookie, name='set_cookie'),
    path('show_cookie/', views.show_cookie, name='show_cookie'),
    path('delete_cookie/', views.delete_cookie, name='delete_cookie'),
    path('set_cookie/', views.set_cookie, name='set_cookie'),
    path('cookie-policy/', views.cookie_policy, name='cookie_policy'),
    path('cookies/', views.cok, name="cookie"),
    path('change_dino_color/', views.change_dino_color, name='change_dino_color'),
    path('dino/', views.pashalka, name='pashalka'), 
    path('map/', views.karta, name='map'), 
    path('profile', views.profile_view, name="profile")

   ]





# Сделал Айхан

more/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User

# Create your models here.

class info(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=355)

class FormsRegister(models.Model):
    full_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=100)
    email = models.EmailField()
    message = models.CharField(max_length=355)

class EmailRegister(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

class VisitCounter(models.Model):
    count = models.PositiveIntegerField(default=0)


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to="media/")
    region = models.CharField(max_length=100, null=True)
    user = models.CharField(max_length=100, null=True) 
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name



class Review(models.Model):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    

    def __str__(self):
        return self.name


class VIPStatus(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    is_vip = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username
    
class DinoSettings(models.Model):
    color = models.CharField(max_length=7, default='#FF5733')  

    def __str__(self):
        return f"Dino color: {self.color}"

more/forms.py
from django import forms
from .models import FormsRegister, Product, EmailRegister, Review


class FormsRegisterForm(forms.ModelForm):
    class Meta:
        model = FormsRegister
        fields = ['full_name', 'phone', 'email', 'message']


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'price', 'image', 'region', 'user']



class EmailRegisterForm(forms.ModelForm):
    class Meta:
        model = EmailRegister
        fields = ['email']


class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['name', 'description']

#  сделал Айхан

more/views.py
import json
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from django.http import HttpResponseRedirect
from django.conf import settings
from .forms import FormsRegisterForm
from django.shortcuts import get_object_or_404, render, redirect,HttpResponseRedirect
from .forms import FormsRegisterForm, ProductForm, EmailRegisterForm, ReviewForm
from .models import Product, Review
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
import stripe
from .models import VIPStatus  
from .models import VIPStatus
import ssl
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods




def home(request):
    reviews = Review.objects.all()
    place = Map(location=[39.770476, 64.445147], zoom_start=17)
    Marker(location=[39.770476, 64.445147], icon=Icon(color='gray')).add_to(place)
    
    place_html = place._repr_html_()
    return render(request, 'home.html', {'reviews': reviews,'place_html': place_html})




def about(request):
    return render(request, 'about.html')


def login(request):
    products = Product.objects.all()

    total_price = sum(product.price for product in products)

    regions = set(product.region for product in products)

    context = {
        'products': products,
        'total_price': total_price,
        'regions': regions,
    }

    return render(request, 'key.html', context)


def politica(request):
    return render(request, 'politica.html')




def review_list(request):
    reviews = Review.objects.all()
    return render(request, 'home.html', {
        'reviews': reviews
    })


def chocolate(request):
    products = Product.objects.all()
    return render(request, 'chocolate.html', {
        'products': products
    })



def contact(request):
    place = Map(location=[39.770476, 64.445147], zoom_start=17)
    Marker(location=[39.770476, 64.445147], icon=Icon(color='gray')).add_to(place)
    
    place_html = place._repr_html_()
    return render(request, 'contact.html', {'place_html': place_html} )


def testimonial(request):
    reviews = Review.objects.all() 
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('more:testimonial')
    else:
        form = ReviewForm()
    return render(request, 'testimonial.html', {
        'form': form,
        'reviews': reviews 
    })





def submit_form(request):
    if request.method == 'POST':
        form = FormsRegisterForm(request.POST)
        if form.is_valid():
            form.save()

            full_name = form.cleaned_data['full_name']
            phone = form.cleaned_data['phone']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            ssl_context = ssl.create_default_context()
            ssl_context.check_hostname = False
            ssl_context.verify_mode = ssl.CERT_NONE

            with smtplib.SMTP(settings.EMAIL_HOST, settings.EMAIL_PORT) as smtp_server:
                smtp_server.starttls(context=ssl_context)
                smtp_server.login(settings.EMAIL_HOST_USER, settings.EMAIL_HOST_PASSWORD)

                msg = MIMEMultipart()
                msg['From'] = settings.EMAIL_HOST_USER
                msg['To'] = 'jumanyyazowayhan32@gmail.com'
                msg['Subject'] = 'Contact Form Submission'

                body = f'Full Name: {full_name}\nPhone: {phone}\nEmail: {email}\nMessage: {message}'
                msg.attach(MIMEText(body, 'plain'))

                smtp_server.send_message(msg)

            return HttpResponseRedirect('/')
    else:
        form = FormsRegisterForm()

    play_sound = True
    return render(request, 'error.html', {'form': form, 'play_sound': play_sound})




def product_form(request):
    if request.method == "POST":
        form = ProductForm(request.POST, request.FILES) 
        if form.is_valid():
            form.save()
            return render(request, 'home.html')
        messages.success(request, 'Продукт успешно добавлен!')
    else:
        form = ProductForm()
    play_sound = True 
    return render(request, 'error.html', {'form': form, 'play_sound': play_sound})


def email_form(request):
    if request.method == "POST":
        form = EmailRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('more:home')
    else:
        form = EmailRegisterForm()
    play_sound = True 
    return render(request, 'error.html', {'form': form, 'play_sound': play_sound})


def review_form(request):
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            if 'image' in request.FILES:
                form.save()
            else:
                Review.objects.create(name=form.cleaned_data['name'], description=form.cleaned_data['description'])
            return redirect('more:home')  
        messages.success(request, 'Отзыв успешно опубликован!')
    else:
        form = ReviewForm()
    play_sound = True 
    return render(request, 'error.html', {'form': form, 'play_sound': play_sound})


def sign_in(request):
    return render(request, 'sign_in.html')

def sign_up(request):
    return render(request, 'sign_up.html')

def log(request):
    return render(request, 'log.html')



# сделал Айхан


def view_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    return render(request, 'product_detail.html', {'product': product})


@login_required  
def buy_vip(request):
    return render(request, 'buy_vip.html')

from django.shortcuts import render, redirect
from django.http import JsonResponse
from django.urls import reverse
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt
import stripe
from .models import VIPStatus

stripe.api_key = settings.STRIPE_SECRET_KEY

@csrf_exempt
def process_payment(request):
    if request.method == 'POST':
        token = request.POST.get('stripeToken')
        amount = 1000 
        if not token:
            return JsonResponse({'error': 'Invalid token'})
        try:
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=[
                    {
                        'price_data': {
                            'currency': 'usd',
                            'product_data': {
                                'name': 'VIP статус',
                            },
                            'unit_amount': amount * 100,  
                        },
                        'quantity': 1,
                    },
                ],
                mode='payment',
                success_url=request.build_absolute_uri(reverse('success_view')) + '?session_id={CHECKOUT_SESSION_ID}',  # URL для успешной оплаты
                cancel_url=request.build_absolute_uri(reverse('profile')),  
            )
            messages.success(request, 'Оплата успешно прошла!')
            return JsonResponse({'sessionId': checkout_session['id']})
        
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=400)

    return JsonResponse({'error': 'Invalid request'})


from django.shortcuts import render, redirect, reverse
from django.http import JsonResponse
from django.http import HttpRequest
from .models import VisitCounter

@login_required
def success_view(request):
    user = request.user

    success = request.GET.get('success')
    vip_status, created = VIPStatus.objects.get_or_create(user=user)
    vip_status.is_vip = True
    vip_status.save()

    visit_counter, created = VisitCounter.objects.get_or_create(id=1)
    visit_counter.count += 1
    visit_counter.save()

    return render(request, 'success.html', {
        'visit_count': visit_counter.count,
        'is_vip': vip_status.is_vip,
    })



from django.http import HttpResponse


def set_cookie(request):
    response = HttpResponse("Cookie set")
    response.set_cookie('user_cookie', 'cookie_value', max_age=3600) 
    return response

def delete_cookie(request):
    response = HttpResponse("Cookie deleted")
    response.delete_cookie('user_cookie')
    return response


def show_cookie(request):
    if 'my_cookie' in request.COOKIES:
        return HttpResponse(f"Value of my_cookie is: {request.COOKIES['my_cookie']}")
    else:
        return HttpResponse("No cookie found.")

def cookie_policy(request):
    return render(request, 'cookie_policy.html')

def cok(request):
    return render(request, 'cok.html')

from django.shortcuts import render
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from .models import DinoSettings

def pashalka(request):
    return render(request, 'pashalka.html')

@csrf_exempt
def change_dino_color(request):
    if request.method == 'POST':
        color = request.POST.get('color')
        DinoSettings.objects.update_or_create(id=1, defaults={'color': color})
        return JsonResponse({'status': 'success', 'color': color})
    return JsonResponse({'status': 'error'})


@login_required
def profile_view(request):
    return render(request, "profile.html")

@login_required
def profile1(request):
    return render(request, "profile.html")


from folium import Map, Marker, Icon

def karta(request):
    place = Map(location=[39.770476, 64.445147], zoom_start=17)
    Marker(location=[39.770476, 64.445147],
           icon=Icon(color='gray')).add_to(place)
    place_html = place._repr_html_()
    return render(request, 'karta.html', {'place_html': place_html})

more/templates/about.html
{% extends 'base.html' %}
{% load static %}
    <!-- about section -->
{% block content %}
    <section class="about_section layout_padding ">
      <div class="container  ">
        <div class="row">
          <div class="col-md-6">
            <div class="detail-box">
              <div class="heading_container">
                <h2>
                  About Our Company
                </h2>
              </div>
              <p>
                Our company provides services of the highest quality. For this reason, we will retain our clients for many years, despite the competition.</p>
              <a href="{% url 'more:politica' %}">
                <span>
                  Read More
                </span>
                <img src="{% static 'images/color-arrow.png' %}" alt="">
              </a>
            </div>
          </div>
          <div class="col-md-6">
            <div class="img-box">
              <img src="{% static 'images/ssea-food.jpg' %}" alt="">
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}
    <!-- end about section -->


    <!-- info section -->
    

more/templates/base.html
{% load static %}
{% load account  %}
{% load socialaccount %}
<!DOCTYPE html>
<html>


<style>
  /* Стили для кнопки переключения темы */
#theme-toggle {
  background: transparent;
  border: none;
  cursor: pointer;
  padding: 5px;
  position: relative;
}

/* Стили для иконки текущей темы */
.theme-icon {
  display: block;
  width: 20px;
  height: 20px;
  background-image: url('path/to/theme-icons.png'); /* Путь к вашим иконкам тем */
  background-position: 0 0; /* Позиция иконки светлой темы */
  background-repeat: no-repeat;
}

/* Стили для иконки темной темы */
body.dark-theme .theme-icon {
  background-position: -20px 0; /* Позиция иконки темной темы */
}

/* Темная тема */
body.dark-theme {
  background-color: #333;
  color: #fff;
}

</style>
<script>
  document.addEventListener('DOMContentLoaded', function() {
    const themeToggle = document.getElementById('theme-toggle');
    const body = document.body;

    themeToggle.addEventListener('click', function() {
        body.classList.toggle('dark-theme');
        updateThemeIcon();
        // Сохраняем выбранную тему в локальном хранилище
        const theme = body.classList.contains('dark-theme') ? 'dark' : 'light';
        localStorage.setItem('theme', theme);
    });

    // Применяем сохраненную тему при загрузке страницы
    const savedTheme = localStorage.getItem('theme');
    if (savedTheme === 'dark') {
        body.classList.add('dark-theme');
        updateThemeIcon();
    }

    function updateThemeIcon() {
        const themeIcon = document.querySelector('.theme-icon');
        if (body.classList.contains('dark-theme')) {
            themeIcon.style.backgroundPosition = '-20px 0'; // Позиция иконки темной темы
        } else {
            themeIcon.style.backgroundPosition = '0 0'; // Позиция иконки светлой темы
        }
    }
});


</script>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Seafoods.com</title>

  <link rel="shortcut icon" href="{% static 'images/logoSeafoods.png' %}" type="image/x-icon">

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  <!--slick slider stylesheet -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.9/slick.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.9/slick-theme.min.css" />

  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:400,600,700&display=swap" rel="stylesheet" />
  <!-- slick slider -->

  <link rel="stylesheet" href="{% static 'css/slick-theme.css' %}" />
  <!-- font awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  <!-- responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />

</head>

<body class="sub_page">
<!--Start of Tawk.to Script-->
<script type="text/javascript">
  var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
  (function(){
  var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
  s1.async=true;
  s1.src='https://embed.tawk.to/660c35081ec1082f04ddfe03/1hqfquaml';
  s1.charset='UTF-8';
  s1.setAttribute('crossorigin','*');
  s0.parentNode.insertBefore(s1,s0);
  })();
  </script>
  <!--End of Tawk.to Script-->
  <div class="main_body_content">

    <div class="hero_area">
      <!-- header section strats -->
      <header class="header_section">
        <div class="container-fluid">
          <nav class="navbar navbar-expand-lg custom_nav-container ">
            <a class="navbar-brand" href="{% url 'more:home' %}">
              Seafood
            </a>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class=""> </span>
            </button>

            <div class="collapse navbar-collapse " id="navbarSupportedContent">
              <ul class="navbar-nav ml-auto">
                <li class="nav-item ">
                  <a class="nav-link"  href="{% url 'more:home' %}" onclick="playSound()">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'more:about' %}" onclick="playSound()"> About</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'more:chocolate' %}" onclick="playSound()">Foods</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'more:testimonial' %}" onclick="playSound()">Testimonial</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'more:contact' %}" onclick="playSound()">Contact Us</a>
                </li>
                <li class="naw-item mt-1">
                  <button id="theme-toggle" aria-label="Toggle theme" onclick="playSound()">
                    <img class="theme-icon" aria-hidden="true" style="height: 30px; width: 30px;" src="{% static 'images/temnyy.png' %}" alt="">
                </button>
                </li>
              </ul>
              <div class="quote_btn-container">
                <h5 class="mt-2">
                  <a onclick="playSound()" href="{% url  'more:key' %}">
                    <i class="fa fa-user" aria-hidden="true"></i>
                    {% if user.is_authenticated %}
                  {% user_display user %}
                  {% endif %}
                  </a>
                </h5>
              </div>
              {% if user.is_authenticated %}
              <form  method="post"  action="/accounts/logout/"> 
                  {% csrf_token %}
                  <button onclick="playSound()" style="background-color: aliceblue; border-radius: 10px; border: none; padding: 5px 7px; color: black;" type="submit">
                      Sign Out   
                  </button>
              </form>
              {% endif %}
              
            </div>
          </nav>
        </div>
      </header>
      <!-- end header section -->
    </div>

    {% block content %}
    {% endblock %}
<section class="info_section layout_padding2">
    <div class="container">
      <div class="row info_form_social_row">
        <div class="col-md-8 col-lg-9">
          <div class="info_form">
           
          </div>
        
      </div>
      <div class="row info_main_row">
        <div class="col-md-6 col-lg-3">
          <div class="info_links">
            <h4>
              Menu
            </h4>
            <div class="info_links_menu">
              <a href="{% url 'more:home' %}">
                Home
              </a>
              <a href="{% url 'more:about' %}">
                About
              </a>
              <a href="{% url 'more:chocolate' %}">
                Foods
              </a>
              <a href="{% url 'more:testimonial' %}">
                Testimonial
              </a>
              <a href="{% url 'more:testimonial' %}">
                Contact us
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="info_insta">
            <h4>
              About us
            </h4>
            <div class="insta_box">
              {% comment %} <div class="img-box">
                <img src="{% static 'images/policy.jpg' %}" alt="">
              </div> {% endcomment %}
              <a style="color: white;" href="{% url 'more:politica' %}">Privacy Policy</a>
            </div>
            
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <div class="info_detail">
            <h4>
              Company
            </h4>
            <p class="mb-0">
              Seafoods is a store specializing in fresh and frozen seafood. The store offers a wide range of products such as fish, seafood, shrimp, mussels, oysters, lobsters and other delicacies from the sea. Seafoods guarantees the high quality of its products, offers a variety of cooking methods and caters to customers of all taste preferences.</p>
          </div>
        </div>
        <div class="col-md-6 col-lg-3">
          <h4>
            Contact Us
          </h4>
          <div class="info_contact">
            <a href="https://yandex.uz/maps/org/monday_academy/122406213969/?display-text=monday%20academy&ll=66.657341%2C37.947875&mode=search&sll=58.219841%2C37.947875&sspn=0.656433%2C0.376810&text=monday%20academy&z=5">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                Location
              </span>
            </a>
            <a href="tel:+998947817447">
              <i class="fa fa-phone" aria-hidden="true"></i>
              <span>
                Call +998 94 781 74 47
              </span>
            </a>
            
            <a href="jumanyyazowayhan32@gmail.com">
              <i class="fa fa-envelope"></i>
              <span>
                jumanyyazowayhan32@gmail.com
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </section>

  <!-- end info_section -->

</div>

<!-- footer section -->
<footer class="container-fluid footer_section">
  <div class="container">
    <div class="col-md-11 col-lg-8 mx-auto">
      <p>
        <strong>© 2024 <a href="https://github.com/ayhandev/">ayhandev</a></strong>
      </p>
    </div>
  </div>
</footer>
<!-- footer section -->

<audio id="buttonSound">
  <source src="{% static 'audio/knop.mp3' %}" type="audio/mpeg">
  Your browser does not support the audio element.
</audio>

<script>
function playSound() {
  var sound = document.getElementById("buttonSound");
  sound.play();
}
</script>
<!-- jQery -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- bootstrap js -->
<script src="{% static 'js/bootstrap.js' %}"></script>
<!-- slick slider -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.5.9/slick.min.js"></script>
<!-- custom js -->
<script src="{% static 'js/custom.js' %}"></script>
<style>

    
  .loader-container {
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: rgba(255, 255, 255, 0.8);
    z-index: 9999;
  }
  
  .loader {
    background-color: #ffffff; /* Белый фон */
    width: 200px;
    text-align: center;
    padding: 20px;
    border-radius: 10px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
  }
  
  .loader h6 {
    margin: 0;
    font-size: 16px;
    color: #333333; /* Темный текст */
  }
  
  .loader img {
    width: 64px;
    margin-top: 20px;
  }
  </style>
  <div class="loader-container" id="loaderContainer">
    <div class="loader">
      <h6>Loading...</h6>
      <span>
        <img src="{% static 'images/loader.gif' %}" alt="Loading Animation">
      </span>
    </div>
  </div>
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const loaderContainer = document.getElementById("loaderContainer");
      const links = document.querySelectorAll("a");
    
      function showLoader() {
        loaderContainer.style.display = "flex";
      }
    
      function hideLoader() {
        loaderContainer.style.display = "none"; 
      }
    
      function checkInternet() {
        const isOnline = window.navigator.onLine;
        if (!isOnline) {
          showLoader(); 
          setTimeout(function() {
            alert('Пожалуйста, проверьте интернет-соединение, затем перезагрузите страницу!');
          }, 10000);
    
          links.forEach(link => {
            link.addEventListener("click", function(event) {
              event.preventDefault(); 
              alert('Проверьте интернет-соединение и перезагрузите страницу, чтобы продолжить!'); 
            });
          });
        } else {
          hideLoader();
        }
      }
    
      checkInternet(); 
    
      setInterval(checkInternet, 1); 
    });
    
    </script>
</body>

</html>

more/templates/contact.html
{% extends 'base.html' %}
{% load static %}
    <!-- contact section -->
{% block content %}
<section class="contact_section layout_padding">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-5 col-lg-4 offset-md-1 offset-lg-2">
        <div class="form_container">
          <div class="heading_container">
            <h2>
              Contact Us
            </h2>
          </div>
          <form method="post" id="form1" action="{% url 'more:submit_form' %}">
            {% csrf_token %}
            <div>
              <input type="text" placeholder="Full Name " name="full_name" />
            </div>
            <div>
              <input type="text" placeholder="Phone number" name="phone" />
            </div>
            <div>
              <input type="email" placeholder="Email" name="email" />
            </div>
            <div>
              <input type="text" class="message-box" placeholder="Message" name="message" />
            </div>
            <div class="d-flex ">
              <button>
                SEND NOW
              </button>
            </div>
          </form>
        </div>
      </div>
      <div class="col-md-6  px-0">
        <div class="map_container">
          <div class="map">
            {{ place_html|safe }}
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

    <!-- end contact section -->


  {% endblock %}

more/templates/karta.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Карта</title>
</head>
<body>
    <!-- Выводим HTML карты -->
    {{ place_html|safe }}
</body>
</html>

more/templates/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Успешная оплата</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f9f9f9;
            margin: 0;
            padding: 0;
        }

        .container {
            max-width: 800px;
            margin: 20px auto;
            background-color: #fff;
            border-radius: 8px;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        }

        h1 {
            font-size: 24px;
            margin-bottom: 20px;
        }

        p {
            margin-bottom: 10px;
        }

        .check-details {
            background-color: #f5f5f5;
            padding: 10px;
            border-radius: 5px;
            margin-top: 20px;
        }

        a {
            display: inline-block;
            padding: 10px 20px;
            background-color: #007bff;
            color: #fff;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 20px;
        }

        a:hover {
            background-color: #0056b3;
        }
    </style>
</head>
<body>
    <div class="container">
        <p>Платеж успешно завершен</p>
        <p>Номер чека: №{{ visit_count }}</p>
        <a href="{% url 'more:key' %}">Перейти в профиль</a>
    </div>
</body>
</html>